//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_21.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserInfo
    {
        [Required] // attributes
        [RegularExpression(@"^[A-Z]+[A-z]{1,30}$")]
        public string FirstName { set; get; }

        [Required]
        [RegularExpression(@"^[A-Z]+[A-z]{1,30}$")]
        public string LastName { set; get; }

        [Required] // attributes
        [RegularExpression(@"^([A-z0-9]{5,30})@([A-z]{3,10}).([a-z]{2,3})$")]
        public string Email { set; get; }

        [Required] // attributes
        [RegularExpression(@"^\d{3}-\d{3}-\d{4}$")]
        public string PhoneNumber { set; get; }

        [Required] // attributes
        [RegularExpression(@"^[A-Z]+[A-z]{1,30}$")]
        public string Password { set; get; }

        [Required] // attributes
        [RegularExpression(@"^(0[1-9]|1[012])[/](0[1-9]|[12][0-9]|3[01])[/](19|20)\d\d$")]
        public string Birthdate { set; get; }

        
    }

}
